### ISSUE TITLE
Convex Hull Crash for rare inputs

### ISSUE THREAD

**Issue by peterstace** [peterstace/simplefeatures#244]
The Convex Hull operation crashes on some inputs. For example: `POLYGON((0.9292893218813453 1.0707106781186548,1.1414213562373097 1,0.07071067811865475 -0.07071067811865475,0 -0.1414213562373095,0.9292893218813453 1.0707106781186548))`.

This was discovered with [cmprefimpl checks when a new test was added for an unrelated change](https://github.com/peterstace/simplefeatures/pull/243).

Crash trace is as follows:

```
cmprefimpl_1  | panic: runtime error: index out of range [-1]
cmprefimpl_1  | 
cmprefimpl_1  | goroutine 1 [running]:
cmprefimpl_1  | github.com/peterstace/simplefeatures/geom.(*pointStack).underTop(...)
cmprefimpl_1  | 	/go/src/github.com/peterstace/simplefeatures/geom/alg_convex_hull.go:134
cmprefimpl_1  | github.com/peterstace/simplefeatures/geom.grahamScan(0xc0001900e0, 0x8, 0x7, 0x7, 0x7, 0xc000623bd0)
cmprefimpl_1  | 	/go/src/github.com/peterstace/simplefeatures/geom/alg_convex_hull.go:182 +0x6ef
cmprefimpl_1  | github.com/peterstace/simplefeatures/geom.convexHull(0x3, 0xc0003d9920, 0xc0003d9920, 0x3)
cmprefimpl_1  | 	/go/src/github.com/peterstace/simplefeatures/geom/alg_convex_hull.go:16 +0x9b
cmprefimpl_1  | github.com/peterstace/simplefeatures/geom.Geometry.ConvexHull(...)
cmprefimpl_1  | 	/go/src/github.com/peterstace/simplefeatures/geom/type_geometry.go:439
cmprefimpl_1  | main.checkConvexHull(0xc0002a8000, 0x3, 0xc0003d9920, 0xc00045c280, 0x0, 0x0)
cmprefimpl_1  | 	/go/src/github.com/peterstace/simplefeatures/internal/cmprefimpl/cmpgeos/checks.go:408 +0x92
cmprefimpl_1  | main.unaryChecks(0xc0002a8000, 0x3, 0xc0003d9920, 0xc00045c280, 0x1, 0x1)
cmprefimpl_1  | 	/go/src/github.com/peterstace/simplefeatures/internal/cmprefimpl/cmpgeos/checks.go:61 +0x5b8
cmprefimpl_1  | main.main()
cmprefimpl_1  | 	/go/src/github.com/peterstace/simplefeatures/internal/cmprefimpl/cmpgeos/main.go:51 +0x4a7
```

**Comment by peterstace** [comment]
Fixed via #245
